name: ci-golang-workflow #Qualquer nome
on: [push] #Ação esperada
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2 #Clonar o repositório
      -uses: actions/setup-go@v2 #Instalar o go
        with:
          go-version: '1.15'      
      -run: go test
      -run: go run math.go
